# ============================================================
# 03_supervisor_multiagent.py
# ─────────────────────────────────────────────────────────────
# SUPERVISOR ARCHITECTURE — the "manager" pattern.
# One supervisor LLM routes tasks to specialized sub-agents.
# Sub-agents report back, supervisor decides what's next.
#
# Architecture:
#
#          ┌─────────────┐
#          │  SUPERVISOR │  ← routes work, synthesizes results
#          └──────┬──────┘
#         ┌───────┼────────┐
#    ┌────▼───┐ ┌─▼──────┐ ┌▼───────┐
#    │RESEARCH│ │ CODER  │ │ WRITER │   ← specialist sub-agents
#    └────────┘ └────────┘ └────────┘
# ============================================================

from config import OPENAI_API_KEY, GPT4O_MINI, GPT4O, console, print_agent_message

from typing import Annotated, Literal, Sequence
from typing_extensions import TypedDict

from langchain_openai import ChatOpenAI
from langchain_core.tools import tool
from langchain_core.messages import BaseMessage, HumanMessage, AIMessage, SystemMessage
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
from langgraph.graph import StateGraph, START, END
from langgraph.graph.message import add_messages
from langgraph.prebuilt import ToolNode
from pydantic import BaseModel
import json


# ── 1. Shared State ───────────────────────────────────────────

class SupervisorState(TypedDict):
    messages: Annotated[list[BaseMessage], add_messages]
    next_agent: str          # which agent runs next
    task: str                # original user task
    research_output: str     # what researcher found
    code_output: str         # what coder produced
    writer_output: str       # what writer created
    final_answer: str        # supervisor's synthesis


# ── 2. Sub-Agent Tools ────────────────────────────────────────

@tool
def search_web(query: str) -> str:
    """Search the web for information."""
    try:
        from duckduckgo_search import DDGS
        with DDGS() as ddgs:
            results = list(ddgs.text(query, max_results=4))
        return "\n\n".join(f"**{r['title']}**\n{r['body']}" for r in results)
    except Exception as e:
        return f"Search error: {e}. Returning mock result for demo: The topic '{query}' is an important area of study."


@tool
def fetch_url(url: str) -> str:
    """Fetch and return the text content of a web page."""
    try:
        import requests
        resp = requests.get(url, timeout=8, headers={"User-Agent": "Mozilla/5.0"})
        # Very basic text extraction
        text = resp.text
        # Remove HTML tags simply
        import re
        text = re.sub(r'<[^>]+>', ' ', text)
        text = re.sub(r'\s+', ' ', text).strip()
        return text[:3000]
    except Exception as e:
        return f"Could not fetch URL: {e}"


@tool
def run_python(code: str) -> str:
    """Execute Python code and return output."""
    import io, sys
    old_stdout = sys.stdout
    sys.stdout = buffer = io.StringIO()
    try:
        import math, json, re
        exec(code, {"__builtins__": __builtins__, "math": math, "json": json, "re": re})
        return buffer.getvalue() or "Executed successfully (no print output)"
    except Exception as e:
        return f"Error: {type(e).__name__}: {e}"
    finally:
        sys.stdout = old_stdout


@tool
def format_document(content: str, format: str = "markdown") -> str:
    """Format and structure content into a professional document."""
    # In production this might call a template engine or document API
    formatted = f"""# Document
    
{content}

---
*Generated by AI Writer Agent*
"""
    return formatted


# ── 3. Individual Sub-Agents ──────────────────────────────────

def make_researcher_agent():
    """Research specialist: searches web, finds facts, summarizes."""
    llm = ChatOpenAI(model=GPT4O_MINI, temperature=0.1, api_key=OPENAI_API_KEY)
    tools = [search_web, fetch_url]
    llm_with_tools = llm.bind_tools(tools)
    tool_node = ToolNode(tools)
    
    system = """You are a Research Specialist Agent. Your job is to:
1. Search for accurate, up-to-date information on topics
2. Summarize findings clearly with sources
3. Identify key facts, statistics, and insights
4. Always be thorough but concise

When you have gathered enough information, provide a structured research report."""

    def researcher_node(state: SupervisorState) -> dict:
        messages = [SystemMessage(content=system)] + state["messages"]
        
        # Run the mini ReAct loop for researcher
        for _ in range(5):  # max 5 tool calls
            response = llm_with_tools.invoke(messages)
            messages.append(response)
            
            if not (hasattr(response, "tool_calls") and response.tool_calls):
                break  # no more tool calls → done
            
            # Execute tools
            tool_results = tool_node.invoke({"messages": messages})
            messages.extend(tool_results["messages"])
        
        research_text = messages[-1].content
        print_agent_message("researcher", f"Research complete: {research_text[:100]}...")
        
        return {
            "messages": [AIMessage(content=f"[RESEARCHER]: {research_text}")],
            "research_output": research_text,
        }
    
    return researcher_node


def make_coder_agent():
    """Code specialist: writes, runs, and debugs Python code."""
    llm = ChatOpenAI(model=GPT4O_MINI, temperature=0, api_key=OPENAI_API_KEY)
    tools = [run_python]
    llm_with_tools = llm.bind_tools(tools)
    tool_node = ToolNode(tools)
    
    system = """You are a Coding Specialist Agent. Your job is to:
1. Write clean, efficient, well-documented Python code
2. Test your code by running it
3. Debug any errors you encounter
4. Explain what the code does and how to use it

Always run your code to verify it works before presenting the final solution."""

    def coder_node(state: SupervisorState) -> dict:
        # Include research output as context if available
        context = ""
        if state.get("research_output"):
            context = f"\n\nContext from research:\n{state['research_output']}"
        
        task_msg = HumanMessage(content=state["task"] + context)
        messages = [SystemMessage(content=system), task_msg]
        
        for _ in range(6):
            response = llm_with_tools.invoke(messages)
            messages.append(response)
            
            if not (hasattr(response, "tool_calls") and response.tool_calls):
                break
            
            tool_results = tool_node.invoke({"messages": messages})
            messages.extend(tool_results["messages"])
        
        code_text = messages[-1].content
        print_agent_message("coder", f"Code complete: {code_text[:100]}...")
        
        return {
            "messages": [AIMessage(content=f"[CODER]: {code_text}")],
            "code_output": code_text,
        }
    
    return coder_node


def make_writer_agent():
    """Writing specialist: synthesizes research into polished content."""
    llm = ChatOpenAI(model=GPT4O_MINI, temperature=0.7, api_key=OPENAI_API_KEY)
    
    system = """You are a Writing Specialist Agent. Your job is to:
1. Take research findings and code examples
2. Synthesize them into clear, engaging, well-structured content
3. Adapt the tone to the audience (technical vs general)
4. Use markdown formatting for readability
5. Produce polished, professional output"""

    def writer_node(state: SupervisorState) -> dict:
        # Gather all previous outputs
        context_parts = []
        if state.get("research_output"):
            context_parts.append(f"Research:\n{state['research_output']}")
        if state.get("code_output"):
            context_parts.append(f"Code:\n{state['code_output']}")
        
        context = "\n\n---\n\n".join(context_parts)
        
        prompt = f"""Task: {state['task']}
        
Available context:
{context}

Please write a comprehensive, well-structured response that incorporates all the above information."""
        
        messages = [SystemMessage(content=system), HumanMessage(content=prompt)]
        response = llm.invoke(messages)
        
        writer_text = response.content
        print_agent_message("writer", f"Writing complete: {writer_text[:100]}...")
        
        return {
            "messages": [AIMessage(content=f"[WRITER]: {writer_text}")],
            "writer_output": writer_text,
        }
    
    return writer_node


# ── 4. Supervisor Agent ───────────────────────────────────────

class RouterDecision(BaseModel):
    """Structured output from supervisor routing."""
    next: Literal["researcher", "coder", "writer", "FINISH"]
    reason: str


def make_supervisor_node():
    """
    The supervisor decides:
    - Which agent to call next
    - When all work is done (FINISH)
    """
    llm = ChatOpenAI(model=GPT4O_MINI, temperature=0, api_key=OPENAI_API_KEY)
    structured_llm = llm.with_structured_output(RouterDecision)
    
    system = """You are a Supervisor Agent managing a team of specialists:
- **researcher**: Searches the web and gathers information
- **coder**: Writes and tests Python code
- **writer**: Creates polished written content

Given the task and what has been done so far, decide who should act next.
Choose FINISH when the task is complete and all necessary work has been done.

Routing guidelines:
- If the task needs information → researcher first
- If the task needs code → coder (after research if needed)
- If output needs to be polished/documented → writer last
- Simple tasks may only need one or two agents
- FINISH when you have everything needed for a complete answer"""

    def supervisor_node(state: SupervisorState) -> dict:
        # Build context summary for supervisor
        done = []
        if state.get("research_output"):
            done.append("✓ Research complete")
        if state.get("code_output"):
            done.append("✓ Code complete")
        if state.get("writer_output"):
            done.append("✓ Writing complete")
        
        status = ", ".join(done) if done else "Nothing done yet"
        
        routing_prompt = f"""Task: {state['task']}
Status: {status}

Who should act next? Choose from: researcher, coder, writer, or FINISH."""
        
        messages = [SystemMessage(content=system), HumanMessage(content=routing_prompt)]
        decision = structured_llm.invoke(messages)
        
        print_agent_message("supervisor", f"Routing to: {decision.next} | Reason: {decision.reason}")
        
        return {"next_agent": decision.next}
    
    return supervisor_node


def synthesize_final_answer(state: SupervisorState) -> dict:
    """Combine all agent outputs into a final response."""
    llm = ChatOpenAI(model=GPT4O_MINI, temperature=0.3, api_key=OPENAI_API_KEY)
    
    outputs = []
    if state.get("research_output"):
        outputs.append(f"Research:\n{state['research_output']}")
    if state.get("code_output"):
        outputs.append(f"Code:\n{state['code_output']}")
    if state.get("writer_output"):
        outputs.append(f"Written Content:\n{state['writer_output']}")
    
    # If writer already produced the final output, use it directly
    if state.get("writer_output"):
        return {"final_answer": state["writer_output"]}
    
    # Otherwise synthesize
    combined = "\n\n---\n\n".join(outputs)
    response = llm.invoke([
        SystemMessage(content="Synthesize the following agent outputs into a cohesive final answer:"),
        HumanMessage(content=combined),
    ])
    return {"final_answer": response.content}


# ── 5. Build the Full Graph ───────────────────────────────────

def build_supervisor_graph():
    
    researcher = make_researcher_agent()
    coder = make_coder_agent()
    writer = make_writer_agent()
    supervisor = make_supervisor_node()
    
    graph = StateGraph(SupervisorState)
    
    # Add all nodes
    graph.add_node("supervisor", supervisor)
    graph.add_node("researcher", researcher)
    graph.add_node("coder", coder)
    graph.add_node("writer", writer)
    graph.add_node("synthesize", synthesize_final_answer)
    
    # Entry: always start with supervisor
    graph.add_edge(START, "supervisor")
    
    # Supervisor routes to sub-agents or synthesis
    graph.add_conditional_edges(
        "supervisor",
        lambda state: state["next_agent"],
        {
            "researcher": "researcher",
            "coder":      "coder",
            "writer":     "writer",
            "FINISH":     "synthesize",
        }
    )
    
    # After each sub-agent, return to supervisor
    graph.add_edge("researcher", "supervisor")
    graph.add_edge("coder",      "supervisor")
    graph.add_edge("writer",     "supervisor")
    
    # Synthesis → END
    graph.add_edge("synthesize", END)
    
    return graph.compile()


# ── 6. Run Demo ───────────────────────────────────────────────

def run_supervisor_demo(task: str):
    console.print(f"\n[bold magenta]═══ 03: Supervisor Multi-Agent ═══[/bold magenta]")
    console.print(f"\n[bold white]TASK:[/bold white] {task}\n")
    
    graph = build_supervisor_graph()
    
    initial_state = {
        "messages": [HumanMessage(content=task)],
        "next_agent": "",
        "task": task,
        "research_output": "",
        "code_output": "",
        "writer_output": "",
        "final_answer": "",
    }
    
    result = graph.invoke(initial_state)
    
    print_agent_message("supervisor", "All agents complete. Final answer:")
    console.print(f"\n[bold green]{'='*60}[/bold green]")
    console.print(result["final_answer"])
    console.print(f"[bold green]{'='*60}[/bold green]")
    
    return result


if __name__ == "__main__":
    # Task 1: Needs researcher + writer
    run_supervisor_demo(
        "Write a brief technical overview of transformer neural networks, "
        "including their key components and why they revolutionized NLP."
    )
    
    # Task 2: Needs coder + writer
    run_supervisor_demo(
        "Write a Python function that implements binary search, "
        "tests it with a sample array, and documents it with examples."
    )
    
    # Task 3: Needs all three agents
    run_supervisor_demo(
        "Research what APIs exist for getting stock prices, "
        "then write Python code to fetch AAPL price using the yfinance library, "
        "and finally write a tutorial explaining how to use it."
    )
